/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description Returns the entity schema for the frontend builder.
         */
        get: operations["simulation_api_get_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Simulation
         * @description Runs a simulation blueprint and returns the recording.
         */
        post: operations["simulation_api_run_simulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BuilderEntitySchema
         * @description Schema for a builder entity definition.
         */
        BuilderEntitySchema: {
            /** Entitytype */
            entityType: string;
            /** Icon */
            icon: string;
            /** Parameters */
            parameters: {
                [key: string]: string;
            };
        };
        /** Blueprint */
        Blueprint: {
            /**
             * Simparams
             * @default {}
             */
            simParams: {
                [key: string]: unknown;
            };
            /**
             * Entities
             * @default []
             */
            entities: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulation_api_get_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuilderEntitySchema"][];
                };
            };
        };
    };
    simulation_api_run_simulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Blueprint"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
