/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description Returns the entity schema for the frontend builder.
         */
        get: operations["simulation_api_get_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Simulation
         * @description Runs a simulation blueprint and returns the recording.
         */
        post: operations["simulation_api_run_simulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BuilderEntitySchema
         * @description Schema for a builder entity definition.
         */
        BuilderEntitySchema: {
            entityType: components["schemas"]["SimulationEntityType"];
            /** Parameters */
            parameters: components["schemas"]["ParameterInfo"][];
        };
        /**
         * ParameterInfo
         * @description Information about a parameter, including its name, type and optional constraints.
         *
         *     This allows for richer parameter definitions beyond just the type,
         *     such as filtering allowed entity types for entity parameters.
         */
        ParameterInfo: {
            /**
             * Name
             * @description The name of the parameter
             */
            name: string;
            /** @description The type of the parameter */
            type: components["schemas"]["ParameterType"];
            /**
             * Allowedentitytypes
             * @description For ENTITY type parameters, optionally restrict which entity types are valid. If None, all entity types are allowed.
             */
            allowedEntityTypes?: components["schemas"]["SimulationEntityType"][] | null;
        };
        /**
         * ParameterType
         * @description Allowed primitive parameter types for builder entities.
         * @enum {string}
         */
        ParameterType: "string" | "number" | "boolean" | "entity";
        /**
         * SimulationEntityType
         * @description Simulation entity types for rendering entities in the frontend.
         * @enum {string}
         */
        SimulationEntityType: "agv" | "robot" | "box" | "palette" | "source" | "sink" | "buffer" | "human" | "counter" | "grid_node" | "";
        /**
         * Metric
         * @description Represents a single metric with columnar tabular data.
         *
         *     A metric has:
         *     - name: Unique identifier for the metric (e.g., "queue_length", "service_time")
         *     - type: MetricType enum value (e.g.: COUNTER, GAUGE, or GENERIC) used for visualization
         *     - labels: Key-value pairs for filtering/grouping (e.g., {"counter_id": "counter_1", "location": "bank"})
         *     - data: Columnar format dictionary where keys are column names and values are lists
         *
         *     Example:
         *         Metric(
         *             name="queue_length",
         *             type=MetricType.GAUGE,
         *             labels={"counter_id": "counter_1"},
         *             data={
         *                 "timestamp": [0.0, 1.5, 3.2, 4.0, 5.5, 6.2],
         *                 "value": [0, 1, 2, 1, 3, 0]
         *             }
         *         )
         */
        Metric: {
            /** Name */
            name: string;
            type: components["schemas"]["MetricType"];
            /**
             * Labels
             * @default {}
             */
            labels: {
                [key: string]: string;
            };
            data: components["schemas"]["MetricData"];
        };
        /**
         * MetricData
         * @description Data of a metric.
         *     Timestamp and value are parallel arrays.
         *
         *     For now only this format is supported
         */
        MetricData: {
            /** Timestamp */
            timestamp: number[];
            /** Value */
            value: number[];
        };
        /**
         * MetricType
         * @description Enumeration of metric types.
         * @enum {string}
         */
        MetricType: "counter" | "gauge" | "sample" | "generic";
        /**
         * MotionSegment
         * @description Describes an entity's position/motion during a time interval.
         *
         *     - entity_id: Unique identifier for the entity
         *     - entity_type: Type for rendering (e.g., "agv", "box", "source")
         *     - parent_id: If set, coordinates are relative to parent; if None, world coordinates
         *     - start_time: When this segment begins
         *     - end_time: When this segment ends (None = until simulation end)
         *     - start_x/y, end_x/y: Position at start and end of segment
         *     - start_angle, end_angle: Rotation at start and end of segment
         *
         *     Position at time t is computed via linear interpolation.
         */
        MotionSegment: {
            /** Entityid */
            entityId: string;
            entityType: components["schemas"]["SimulationEntityType"];
            /** Parentid */
            parentId?: string | null;
            /** Starttime */
            startTime: number;
            /** Endtime */
            endTime?: number | null;
            /** Startx */
            startX: number;
            /** Starty */
            startY: number;
            /** Endx */
            endX: number;
            /** Endy */
            endY: number;
            /**
             * Startangle
             * @default 0
             */
            startAngle: number;
            /**
             * Endangle
             * @default 0
             */
            endAngle: number;
        };
        /**
         * SimulationRecording
         * @description Complete recording of a simulation run.
         *
         *     For each component there is a sequence of records
         *     where the start time of each record needs to be higher than
         *     start time of previous one for the same component.
         *
         *     Notes:
         *     - new record invalidates the previous one
         *     - to record stay in location, use the same start and end time and coordinates
         *     - to stay indefinitely, use None for end time
         *     - to stop rendering of an entity use same start and end time
         */
        SimulationRecording: {
            /** Duration */
            duration: number;
            /**
             * Segments By Entity
             * @default {}
             */
            segments_by_entity: {
                [key: string]: components["schemas"]["MotionSegment"][];
            };
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["Metric"][];
        };
        /**
         * Blueprint
         * @description Simulation blueprint used by the engine.
         *
         *     This mirrors the structure expected by destiny_sim.builder.runner.run_blueprint
         *     and by the frontend builder feature.
         */
        Blueprint: {
            /**
             * @default {
             *       "initialTime": null,
             *       "duration": null
             *     }
             */
            simParams: components["schemas"]["SimParams"];
            /**
             * Entities
             * @default []
             */
            entities: components["schemas"]["BlueprintEntity"][];
        };
        /**
         * BlueprintEntity
         * @description Single entity instance in a simulation blueprint.
         */
        BlueprintEntity: {
            entityType: components["schemas"]["SimulationEntityType"];
            /** Uuid */
            uuid: string;
            /** Parameters */
            parameters: components["schemas"]["BlueprintEntityParameter"][];
        };
        /**
         * BlueprintEntityParameter
         * @description Single parameter for a blueprint entity.
         */
        BlueprintEntityParameter: {
            /**
             * Name
             * @description The name of the parameter
             */
            name: string;
            /** @description PRIMITIVE or ENTITY */
            parameterType: components["schemas"]["BlueprintParameterType"];
            /**
             * Value
             * @description The parameter value (primitive value or UUID string for entities)
             */
            value: string | number | boolean;
        };
        /**
         * BlueprintParameterType
         * @description Parameter type for blueprint entity parameters.
         * @enum {string}
         */
        BlueprintParameterType: "primitive" | "entity";
        /**
         * SimParams
         * @description Simulation-level parameters shared between frontend and engine.
         */
        SimParams: {
            /** Initialtime */
            initialTime?: number | null;
            /** Duration */
            duration?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulation_api_get_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuilderEntitySchema"][];
                };
            };
        };
    };
    simulation_api_run_simulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Blueprint"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRecording"];
                };
            };
        };
    };
}
