/**
 * Schema definitions for the drag-and-drop scenario builder.
 */

import type { components } from "@/types/api";

/**
 * Parameter type definitions for builder entities.
 * Primitive types supported by the builder.
 * These match the string values returned by the API.
 */
export type ParameterType = "string" | "number" | "boolean";

/**
 * Parameter value can be a string, number, or boolean.
 */
export type ParameterValue = string | number | boolean;

/**
 * Builder Entity Schema - defines what entities can be used in the builder,
 * their icons, and what parameters they accept.
 * 
 * This type is compatible with the OpenAPI-generated BuilderEntitySchema,
 * but provides more specific typing for the parameters field.
 */
export interface BuilderEntitySchema // todo: get rid of this - probly nicer schema on BE
  extends Omit<components["schemas"]["BuilderEntitySchema"], "parameters"> {
  /** Parameters this entity accepts, mapping parameter name to its type string */
  parameters: Record<string, ParameterType>;
}

/**
 * Simulation Blueprint - JSON representation of the initial state of a simulation.
 * This is what gets generated by the builder and consumed by the engine.
 */
export interface SimulationBlueprint {
  /** Simulation-level parameters (e.g., duration, initial time) */
  simParams: {
    /** Initial simulation time (default: 0) */
    initialTime?: number;
    /** Maximum simulation duration (optional) */
    duration?: number;
  };
  /** List of entities in the simulation */
  entities: BlueprintEntity[];
}

/**
 * An entity instance in the blueprint.
 */
export interface BlueprintEntity {
  /** The type of entity */
  entityType: string;
  /** Unique identifier for this entity instance */
  uuid: string;
  /** Parameter values for this entity */
  parameters: Record<string, ParameterValue>;
}
