
/**
 * Schema definitions for the drag-and-drop scenario builder.
 */

/**
 * Parameter type definitions for builder entities.
 * Primitive types supported by the builder.
 */
export type ParameterType = "string" | "number";

/**
 * Parameter value can be a string or number.
 */
export type ParameterValue = string | number;

/**
 * Builder Entity Schema - defines what entities can be used in the builder,
 * their icons, and what parameters they accept.
 */
export interface BuilderEntitySchema {
  /** The type of entity (e.g., "human", "agv", "robot") */
  entityType: string;
  /** Path to the icon/image asset for this entity */
  icon: string;
  /** Parameters this entity accepts, mapping parameter name to its type */
  parameters: Record<string, ParameterType>;
}

/**
 * Simulation Blueprint - JSON representation of the initial state of a simulation.
 * This is what gets generated by the builder and consumed by the engine.
 */
export interface SimulationBlueprint {
  /** Simulation-level parameters (e.g., duration, initial time) */
  simParams: {
    /** Initial simulation time (default: 0) */
    initialTime?: number;
    /** Maximum simulation duration (optional) */
    duration?: number;
  };
  /** List of entities in the simulation */
  entities: BlueprintEntity[];
}

/**
 * An entity instance in the blueprint.
 */
export interface BlueprintEntity {
  /** The type of entity */
  entityType: string;
  /** Unique identifier for this entity instance */
  uuid: string;
  /** Parameter values for this entity */
  parameters: Record<string, ParameterValue>;
}
